baseURL = 'https://www.stevenedu.cn'
languageCode = 'zh-CN'
title = 'My New Hugo Site'
theme = "stack"

[build]
  publishDir = 'public'
  
[params]
  description = "技术博客"
  
[markup]
  [markup.highlight]
    style = 'github'