[build]
  command = "hugo"  # 移除 npm run build:admin &&
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.145.0"
  
[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo -b $DEPLOY_PRIME_URL"