[build]
  command = "npm run build:admin && hugo"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.145.0"
  
[context.deploy-preview]
  command = "npm run build:admin && hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "npm run build:admin && hugo -b $DEPLOY_PRIME_URL"