backend:
  name: github
  repo: yourusername/yourrepo  # 替换为你的 GitHub 用户名和仓库名
  branch: main                 # 如果你使用的分支不是 main，请修改为相应分支
  auth_scope: repo             # 允许 NetlifyCMS 操作你的仓库
  client_id: Ov23li5B3VKf6Y1lfyZr
collections:
  - name: "posts"
    label: "文章"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "日期", name: "date", widget: "datetime" }
      - { label: "内容", name: "body", widget: "markdown" }
