backend:
  name: github
  repo: Alpha19970221/my-tech-blog  # 替换为你的 GitHub 用户名和仓库名
  branch: main                      # 如你的分支不是 main，请修改为相应分支
  auth_scope: repo                  # 允许 Decap CMS 操作你的仓库

# 如果要在本地环境测试 CMS
# local_backend: true

# 媒体文件设置
media_folder: "static/images/uploads"  # 媒体文件在仓库中的存放路径
public_folder: "/images/uploads"       # 网站中引用媒体文件的路径

# 内容集合定义
collections:
  - name: "posts"
    label: "文章"
    folder: "content/posts"         # 文章存放的位置
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "更新日期", name: "lastmod", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false, required: false }
      - { label: "草稿", name: "draft", widget: "boolean", default: false, required: false }
      - { label: "文章描述", name: "description", widget: "text", required: false }
      - { label: "特色图片", name: "featuredImage", widget: "image", required: false }
      - { label: "分类", name: "categories", widget: "list", required: false }
      - { label: "标签", name: "tags", widget: "list", required: false }
      - { label: "内容", name: "body", widget: "markdown" }

  - name: "pages"
    label: "页面"
    folder: "content"
    create: true
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "内容", name: "body", widget: "markdown" }